-- Tests for core.clock — pure chess-clock accounting.

local Clock = require("core.clock")

local function withClock(control)
    local t = { now = 1000 }
    local clock = Clock:new(control, { now = function() return t.now end })
    return clock, function(seconds) t.now = t.now + seconds end
end

describe("Clock", function()
    it("starts with base times and stopped", function()
        local clock = Clock:new({ base = { w = 300, b = 300 }, increment = { w = 5, b = 5 } },
            { now = function() return 0 end })
        assert.is_false(clock.running)
        assert.equals(300, clock:remaining("w"))
        assert.equals(300, clock:remaining("b"))
        assert.equals("w", clock.turn)
    end)

    it("counts down the running player's time", function()
        local clock, advance = withClock({ base = { w = 300, b = 300 }, increment = { w = 0, b = 0 } })
        clock:start()
        advance(10)
        assert.equals(290, clock:remaining("w"))
        assert.equals(300, clock:remaining("b"))
    end)

    it("banks increment on stop", function()
        local clock, advance = withClock({ base = { w = 300, b = 300 }, increment = { w = 5, b = 5 } })
        clock:start()
        advance(10)
        clock:stop()
        assert.equals(295, clock:remaining("w")) -- 300 - 10 + 5
        assert.is_false(clock.running)
    end)

    it("switch hands the clock over with increment banked", function()
        local clock, advance = withClock({ base = { w = 300, b = 300 }, increment = { w = 5, b = 5 } })
        clock:start()
        advance(12)
        clock:switch()
        assert.equals("b", clock.turn)
        assert.equals(293, clock:remaining("w")) -- banked at switch: 300 - 12 + 5
        assert.is_true(clock.running)
        advance(3)
        assert.equals(297, clock:remaining("b"))
    end)

    it("clamps remaining time at zero", function()
        local clock, advance = withClock({ base = { w = 10, b = 300 }, increment = { w = 0, b = 0 } })
        clock:start()
        advance(600)
        assert.equals(0, clock:remaining("w"))
        assert.is_true(clock:expired())
    end)

    it("is not expired when stopped", function()
        local clock, advance = withClock({ base = { w = 10, b = 300 }, increment = { w = 0, b = 0 } })
        clock:start()
        advance(600)
        clock:stop()
        assert.is_false(clock:expired())
    end)

    it("reset restores base times with White on move", function()
        local clock = withClock({ base = { w = 300, b = 300 }, increment = { w = 5, b = 5 } })
        clock:start()
        clock:switch()
        clock:reset()
        assert.equals(300, clock:remaining("w"))
        assert.equals(300, clock:remaining("b"))
        assert.equals("w", clock.turn)
        assert.is_false(clock.running)
    end)

    it("setTurn changes the side without banking", function()
        local clock = withClock({ base = { w = 300, b = 300 }, increment = { w = 5, b = 5 } })
        clock:setTurn("b")
        assert.equals("b", clock.turn)
        assert.equals(300, clock:remaining("b"))
    end)

    it("setTime overrides banked time (restore)", function()
        local clock = withClock({ base = { w = 300, b = 300 }, increment = { w = 5, b = 5 } })
        clock:setTime("b", 123)
        assert.equals(123, clock:remaining("b"))
        clock:setTime("b", -5)
        assert.equals(0, clock:remaining("b"))
    end)

    it("formats hh:mm:ss", function()
        assert.equals("00:00:05", Clock.format(5))
        assert.equals("00:05:00", Clock.format(300))
        assert.equals("01:30:00", Clock.format(5400))
        assert.equals("00:00:00", Clock.format(0))
        assert.equals("00:00:00", Clock.format(-3))
        assert.equals("00:00:00", Clock.format(nil))
    end)
end)
