-- Tests for core.game — the chess rules facade.

local Game = require("core.game")

describe("Game", function()
    describe("initial position", function()
        it("starts from the standard FEN", function()
            local game = Game:new()
            assert.equals("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1", game:fen())
            assert.equals(Game.WHITE, game:turn())
            assert.falsy(game:inCheck())
        end)

        it("accepts a FEN", function()
            local game = Game:new({ fen = "7k/5Q2/6K1/8/8/8/8/8 b - - 0 1" })
            assert.equals("7k/5Q2/6K1/8/8/8/8/8 b - - 0 1", game:fen())
            assert.equals(Game.BLACK, game:turn())
        end)

        it("defaults roles to human white vs computer black", function()
            local game = Game:new()
            assert.is_true(game:isHuman(Game.WHITE))
            assert.is_false(game:isHuman(Game.BLACK))
            assert.is_true(game:isHumanVsComputer())
            assert.is_false(game:isHumanVsHuman())
            assert.is_false(game:isComputerVsComputer())
        end)

        it("updates roles", function()
            local game = Game:new()
            game:setHuman(Game.BLACK, true)
            assert.is_true(game:isHumanVsHuman())
            game:setHuman(Game.WHITE, false)
            game:setHuman(Game.BLACK, false)
            assert.is_true(game:isComputerVsComputer())
            assert.is_false(game:isHumanVsComputer())
            game:setHuman(Game.WHITE, true)
            game:setHuman(Game.BLACK, false)
            assert.is_true(game:isHumanVsComputer())
        end)

        it("rejects invalid colors for roles", function()
            local game = Game:new()
            assert.has_error(function() game:isHuman("green") end)
            assert.has_error(function() game:setHuman("green", true) end)
        end)
    end)

    describe("playing moves", function()
        it("plays a SAN move", function()
            local game = Game:new()
            local move = game:playMove("e4")
            assert.equals("e4", move.san)
            assert.equals("e2", move.from)
            assert.equals("e4", move.to)
        end)

        it("plays a UCI move", function()
            local game = Game:new()
            local move = game:playUci("e2e4")
            assert.equals("e4", move.san)
        end)

        it("plays a promotion", function()
            local game = Game:new({ fen = "8/P7/8/8/8/8/k1K5/8 w - - 0 1" })
            local move = game:playUci("a7a8q")
            assert.equals("a8=Q#", move.san) -- mate by promotion in this position
            assert.equals("q", move.promotion)
        end)

        it("rejects illegal moves", function()
            local game = Game:new()
            assert.is_nil(game:playMove("e5"))
            assert.is_nil(game:playUci("e2e5"))
            assert.is_nil(game:playUci("banana"))
            assert.is_nil(game:playMove("banana"))
        end)

        it("tracks the move history as SAN and UCI", function()
            local game = Game:new()
            game:playMove("e4")
            game:playMove("e5")
            game:playMove("Nf3")
            assert.same({ "e4", "e5", "Nf3" }, game:sanHistory())
            assert.same({ "e2e4", "e7e5", "g1f3" }, game:uciMoveList())
            assert.equals("e2e4 e7e5 g1f3", game:uciMoveString())
        end)

        it("clears the redo stack on a new move", function()
            local game = Game:new()
            game:playMove("e4")
            game:playMove("e5")
            game:undo()
            game:playMove("c5")
            assert.is_nil(game:redo())
            assert.same({ "e4", "c5" }, game:sanHistory())
        end)

        it("lastMove returns the most recent move", function()
            local game = Game:new()
            assert.is_nil(game:lastMove())
            game:playMove("e4")
            game:playMove("e5")
            local move = game:lastMove()
            assert.equals("e7", move.from)
            assert.equals("e5", move.to)
        end)
    end)

    describe("undo and redo", function()
        it("undo takes back a move and restores the position", function()
            local game = Game:new()
            game:playMove("e4")
            local move = game:undo()
            assert.equals("e4", move.san)
            assert.equals("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1", game:fen())
        end)

        it("redo replays an undone move", function()
            local game = Game:new()
            game:playMove("e4")
            game:undo()
            local move = game:redo()
            assert.equals("e4", move.san)
            assert.equals(Game.BLACK, game:turn())
        end)

        it("undo past the start of the game returns nil", function()
            local game = Game:new()
            assert.is_nil(game:undo())
            game:playMove("d4")
            game:undo()
            assert.is_nil(game:undo())
        end)

        it("redo with nothing to redo returns nil", function()
            local game = Game:new()
            assert.is_nil(game:redo())
        end)

        it("reset clears history and redo", function()
            local game = Game:new()
            game:playMove("e4")
            game:playMove("e5")
            game:undo()
            game:reset()
            assert.same({}, game:sanHistory())
            assert.is_nil(game:redo())
            assert.equals("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1", game:fen())
        end)
    end)

    describe("status", function()
        it("is not over in the initial position", function()
            local game = Game:new()
            local status = game:status()
            assert.is_false(status.over)
            assert.is_nil(status.result)
            assert.is_nil(status.reason)
        end)

        it("detects checkmate (fool's mate)", function()
            local game = Game:new()
            game:playMove("f3")
            game:playMove("e5")
            game:playMove("g4")
            game:playMove("Qh4#")
            local status = game:status()
            assert.is_true(status.over)
            assert.equals("0-1", status.result)
        end)

        it("detects stalemate", function()
            local game = Game:new({ fen = "7k/5Q2/6K1/8/8/8/8/8 b - - 0 1" })
            local status = game:status()
            assert.is_true(status.over)
            assert.equals("1/2-1/2", status.result)
            assert.equals("Stalemate", status.reason)
        end)

        it("detects check", function()
            local game = Game:new({ fen = "rnb1kbnr/pppp1ppp/8/4p3/6Pq/5P2/PPPPP2P/RNBQKBNR w KQkq - 1 3" })
            assert.is_true(game:inCheck())
        end)
    end)

    describe("PGN", function()
        it("round-trips a played game", function()
            local game = Game:new()
            game:playMove("e4")
            game:playMove("e5")
            game:playMove("Nf3")
            game:playMove("Nc6")
            local pgn = game:pgn()

            local reloaded = Game:new()
            local ok, err = reloaded:loadPgn(pgn)
            assert.is_true(ok, err)
            assert.same({ "e4", "e5", "Nf3", "Nc6" }, reloaded:sanHistory())
        end)

        it("tolerates garbage instead of throwing", function()
            local game = Game:new()
            assert.has_no_error(function() game:loadPgn("this is not a pgn at all !!!") end)
        end)

        it("clears the redo stack on load", function()
            local game = Game:new()
            game:playMove("e4")
            game:playMove("e5")
            game:undo()
            game:loadPgn("1. d4 d5")
            assert.is_nil(game:redo())
            assert.same({ "d4", "d5" }, game:sanHistory())
        end)
    end)
end)
